// services/questions.js — Rich, specific, university-student-focused questions

export const SECTIONS = [
  {
    id: 'stress',
    title: 'Stress & Pressure',
    subtitle: "Let's understand what's weighing on you right now.",
    icon: '🌊',
    color: 'teal',
    questions: [
      {
        id: 'stress_level',
        text: 'Over the past 2 weeks, how often have you felt unable to control the important things in your life?',
        hint: 'Think about deadlines, exams, personal responsibilities.',
        type: 'scale', min: 1, max: 10,
        labels: { 1: 'Almost never', 10: 'Almost every day' },
      },
      {
        id: 'financial_stress',
        text: 'How much is financial pressure (tuition, living costs, part-time work) affecting your daily life?',
        hint: 'Consider whether money worries are distracting you from studies or sleep.',
        type: 'scale', min: 1, max: 10,
        labels: { 1: 'Not affecting me', 10: 'Severely affecting me' },
      },
      {
        id: 'semester_credit_load',
        text: 'How many credit hours are you enrolled in this semester?',
        hint: 'A typical full-time load is 15-18 credits.',
        type: 'radio',
        options: [
          { label: '1-9 credits (part-time)',        value: 6  },
          { label: '10-15 credits (normal load)',    value: 12 },
          { label: '16-18 credits (heavy load)',     value: 17 },
          { label: '19+ credits (overloaded)',       value: 21 },
        ],
      },
    ],
  },
  {
    id: 'sleep',
    title: 'Sleep & Physical Health',
    subtitle: "Your body's recovery directly shapes your mental state.",
    icon: '🌙',
    color: 'sage',
    questions: [
      {
        id: 'sleep_quality',
        text: 'How would you describe your sleep over the past week?',
        hint: 'Consider how rested you feel in the morning, not just hours slept.',
        type: 'radio',
        options: [
          { label: 'Restorative — I wake up refreshed',           value: 9 },
          { label: 'Okay — some nights better than others',        value: 6 },
          { label: 'Poor — I wake up tired most mornings',         value: 4 },
          { label: 'Very poor — I barely sleep or sleep too much', value: 2 },
        ],
      },
      {
        id: 'physical_activity',
        text: 'How many days per week do you do at least 20 minutes of physical movement?',
        hint: 'Walking, gym, sports, yoga — anything that gets you moving counts.',
        type: 'radio',
        options: [
          { label: 'Never or rarely',  value: 2 },
          { label: '1-2 days a week',  value: 4 },
          { label: '3-4 days a week',  value: 7 },
          { label: '5+ days a week',   value: 10 },
        ],
      },
      {
        id: 'diet_quality',
        text: 'How would you describe your eating habits as a student?',
        hint: 'Stress eating, skipping meals, and late-night snacks all count.',
        type: 'radio',
        options: [
          { label: 'Balanced — I eat regular, nutritious meals',       value: 9 },
          { label: 'Okay — mostly fine but skipping meals sometimes',   value: 6 },
          { label: 'Poor — mostly takeaway, skipping meals often',      value: 4 },
          { label: 'Very poor — living on caffeine and snacks',         value: 2 },
        ],
      },
    ],
  },
  {
    id: 'academic',
    title: 'Academic Wellbeing',
    subtitle: 'How your studies are affecting your mental health.',
    icon: '📚',
    color: 'teal',
    questions: [
      {
        id: 'depression_score',
        text: 'In the past 2 weeks, how often have you felt little interest or pleasure in doing things — including things you used to enjoy?',
        hint: 'This includes hobbies, socialising, studying topics you once liked.',
        type: 'scale', min: 1, max: 10,
        labels: { 1: 'Rarely / Never', 10: 'Nearly every day' },
      },
      {
        id: 'extracurricular_involvement',
        text: 'Are you involved in any clubs, societies, sports teams, or volunteer work?',
        hint: 'Extracurricular activities help build identity and reduce burnout.',
        type: 'radio',
        options: [
          { label: 'Very actively (multiple activities)',  value: 9 },
          { label: 'Somewhat (one activity)',              value: 6 },
          { label: 'Not currently, but I want to be',      value: 4 },
          { label: 'No, and not interested right now',     value: 2 },
        ],
      },
      {
        id: 'counseling_service_use',
        text: "Have you ever used counseling, therapy, or mental health support services?",
        hint: 'There is no right or wrong answer — this helps us understand your support history.',
        type: 'yesno',
        trueValue: true, falseValue: false,
        yesLabel: 'Yes, I have used them',
        noLabel: "No, I haven't",
      },
    ],
  },
  {
    id: 'social',
    title: 'Social Life & Relationships',
    subtitle: 'Connection is one of the most powerful protectors of mental health.',
    icon: '🤝',
    color: 'sage',
    questions: [
      {
        id: 'social_support',
        text: "If you were having a really hard week, how confident are you that someone would be there to support you?",
        hint: 'Think about friends, family, a mentor, or even a flatmate.',
        type: 'scale', min: 1, max: 10,
        labels: { 1: 'I feel completely alone', 10: 'I have strong support around me' },
      },
      {
        id: 'relationship_status',
        text: 'What is your current relationship status?',
        hint: 'Relationship dynamics can significantly affect mental health.',
        type: 'radio',
        options: [
          { label: 'Single',                               value: 'single' },
          { label: 'In a relationship',                    value: 'in_relationship' },
          { label: 'Married',                              value: 'married' },
          { label: 'Going through a break-up or complicated', value: 'divorced' },
        ],
      },
      {
        id: 'substance_use',
        text: 'Do you use alcohol, tobacco, or other substances to cope with stress, anxiety, or loneliness?',
        hint: 'This is a safe space. Honest answers lead to better personalised support.',
        type: 'yesno',
        trueValue: true, falseValue: false,
        yesLabel: 'Yes, sometimes or often',
        noLabel: "No, I don't",
      },
    ],
  },
  {
    id: 'emotional',
    title: 'Emotional Wellbeing',
    subtitle: 'Understanding your inner emotional landscape.',
    icon: '💚',
    color: 'teal',
    questions: [
      {
        id: 'anxiety_score',
        text: 'How often do you experience worry, nervousness, or a sense of dread that is hard to switch off?',
        hint: 'Before exams, presentations, social situations, or for no clear reason.',
        type: 'scale', min: 1, max: 10,
        labels: { 1: 'Very rarely', 10: 'Almost constantly' },
      },
      {
        id: 'family_history',
        text: 'Has anyone in your immediate family been diagnosed with or treated for depression, anxiety, or another mental health condition?',
        hint: 'Family history is a known risk factor — this helps calibrate your assessment.',
        type: 'yesno',
        trueValue: true, falseValue: false,
        yesLabel: 'Yes',
        noLabel: "No / I'm not sure",
      },
      {
        id: 'chronic_illness',
        text: 'Do you live with any chronic physical health condition (e.g. diabetes, asthma, chronic pain, autoimmune conditions)?',
        hint: 'Physical and mental health are deeply connected.',
        type: 'yesno',
        trueValue: true, falseValue: false,
        yesLabel: 'Yes',
        noLabel: 'No',
      },
      {
        id: 'free_text',
        text: "In your own words — How are you feeling right now?",
        hint: 'Your response is private and only used to personalise your support.',
        type: 'textarea',
        placeholder: "e.g. \"I've been struggling to keep up with assignments since my part-time job hours increased, and I feel like I'm falling behind everyone else...\"",
      },
    ],
  },
]

export const SECTION_LABELS = {
  stress_level:     'Stress & Pressure',
  sleep_quality:    'Sleep & Physical Health',
  depression_score: 'Academic Wellbeing',
  social_support:   'Social Life & Relationships',
  anxiety_score:    'Emotional Wellbeing',
}
